- name: Installing docker and setting up dependencies
  ansible.builtin.shell: |
    set -e
    sudo apt update
    sudo mkdir -p /home/adminuser/data/mongodb
    sudo mkdir -p /home/adminuser/data/nginx
    sudo apt install ca-certificates curl
    sudo apt install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
    sudo install -m 0755 -d /etc/apt/keyrings
    sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
    sudo chmod a+r /etc/apt/keyrings/docker.asc
    sudo tee /etc/apt/sources.list.d/docker.sources <<EOF
    Types: deb
    URIs: https://download.docker.com/linux/ubuntu
    Suites: $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}")
    Components: stable
    Architectures: $(dpkg --print-architecture)
    Signed-By: /etc/apt/keyrings/docker.asc
    EOF
    sudo apt update

- name: Docker login
  community.docker.docker_login:
    username: "{{ USERNAME }}"
    password: "{{ DOCKER_TOKEN }}"

- name: Copying Docker compose file
  ansible.builtin.copy:
    src: ./../DockerContainers/docker-compose.yml
    dest: /home/adminuser/multi-container
    force: yes

- name: Copying secrets folder
  ansible.builtin.copy:
    src: ./../DockerContainers/API/secrets
    dest: /home/adminuser/multi-container/DockerContainers/API
    force: yes

- name: Start app with Compose
  community.docker.docker_compose_v2:
    project_src: /home/adminuser/multi-container
    state: present
    wait: false
    build: always
    recreate: auto
  environment:
    MONGO_DATA_PATH: /home/adminuser/data/mongodb
    NGINX_DATA_PATH: /home/adminuser/data/nginx

- name: Force stop all containers
  shell: "docker stop $(docker ps -q)"
  tags: [never, stop]
